### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by jantotof** [exoscale/php-weathermap#1]
I want to use [Sourcegraph](https://sourcegraph.com) for php-weathermap code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/exoscale/php-weathermap. (It should only take 30 seconds.)

Thank you!

**Comment by retrack** [comment]
this is some kind of automated request. Closing, sourcegraph does not even support php at this time.
