### ISSUE TITLE
BW*COLOR 

### ISSUE THREAD

**Issue by V5ctor** [exoscale/php-weathermap#2]
Hi, 

I would like to change the color of the background and the font of the box on links (Just see on the picture below). I tried to add `BW*COLOR #000000` to my link's edit window, but nothing happens.
Could you give me the right syntax, I cannot find something in the config reference page on 
`http://network-weathermap.com/manual/0.97b/pages/config-reference.htm`

Best regards 

Victor 

![howto](https://cloud.githubusercontent.com/assets/18124387/23669079/53c3e3e2-0363-11e7-9188-ce7b738b3d36.png)

**Comment by llambiel** [comment]
Hi,

You may try BWBOXCOLOR https://network-weathermap.com/manual/0.98/pages/config-reference.html#LINK_COLORS and BWFONT https://network-weathermap.com/manual/0.98/pages/config-reference.html#LINK_BWFONT

Hope that helps.

**Comment by V5ctor** [comment]
Perfect, thanks for your help. 👍
